name: navigation_patterns
description: Common reusable patterns for handling navigation in a complex app
version: 0.0.1
repository: https://github.com/JonasWanke/navigation_patterns
publish_to: none

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: '>=3.7.0 <3.8.0'

dependencies:
  black_hole_flutter: ^0.3.0
  flutter:
    sdk: flutter
  meta: ^1.3.0

dev_dependencies:
  dart_code_metrics: ^5.0.1
  flutter_lints: ^2.0.1
