name: navigation_patterns
description: "🗺 This package implements common reusable patterns for handling navigation in a complex app."
version: 0.0.1
homepage: https://github.com/JonasWanke/navigation_patterns

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  black_hole_flutter: ^0.2.10
  dartx: ^0.5.0
  flutter:
    sdk: flutter
  meta: ^1.1.8

dev_dependencies:
  extra_pedantic: ^1.2.0
  test: ^1.6.0
